spring:
  # 数据库
  datasource:
    username: root
    password: chenbing
    url: jdbc:mysql://localhost:3306/rms_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name:
  # 国际化
  messages:
    basename: i18n.login
  # redis
  redis:
    host: localhost
    port: 6379

# mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
